services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: tibiacore
    volumes:
      - tibiacore_data:/var/lib/mysql
      - ./tibiacore.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_root_password.txt:/run/secrets/mysql_root_password:ro
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: myaac-web-container
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: tibiacore
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - ./myaac-1.7.1/:/var/www/html/:rw
      - ./mysql_root_password.txt:/run/secrets/mysql_root_password:ro 
      - ./config.lua:/var/www/html/config.lua:rw
      - ./tibiacore.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/var/www/html/data/:rw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myaac-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "8080:80"
    volumes:
      - ./mysql_root_password.txt:/run/secrets/mysql_root_password:ro

volumes:
  tibiacore_data:
